using DnsmasqWebUI.Infrastructure.Services.Dnsmasq.Filters;
using DnsmasqWebUI.Models.Dnsmasq;
using DnsmasqWebUI.Models.Dnsmasq.EffectiveConfig;
using DnsmasqWebUI.Models.Filters;
using Xunit;

namespace DnsmasqWebUI.Tests.Services.Filters;

public class FiltersPageProjectionServiceTests
{
    private static DnsmasqServiceStatus MinimalStatus(
        IReadOnlyList<string> addresses,
        IReadOnlyList<ValueWithSource>? addressSources = null)
    {
        var cfg = TestConfig(addresses);
        var sources = addressSources != null && addressSources.Count == addresses.Count
            ? MinimalSources(addressSources)
            : null;
        return EmptyStatus() with { EffectiveConfig = cfg, EffectiveConfigSources = sources };
    }

    private static EffectiveConfigSources MinimalSources(IReadOnlyList<ValueWithSource> addressValues) =>
        new(
            NoHosts: null,
            AddnHostsPaths: [],
            HostsdirPath: null,
            ServerValues: [],
            LocalValues: [],
            RevServerValues: [],
            AddressValues: addressValues,
            Interfaces: [],
            ListenAddresses: [],
            ExceptInterfaces: [],
            DhcpRanges: [],
            DhcpHostLines: [],
            DhcpOptionLines: [],
            DhcpMatchValues: [],
            DhcpBootValues: [],
            DhcpIgnoreValues: [],
            DhcpVendorclassValues: [],
            DhcpUserclassValues: [],
            RaParamValues: [],
            SlaacValues: [],
            PxeServiceValues: [],
            TrustAnchorValues: [],
            ResolvFiles: [],
            RebindDomainOkValues: [],
            BogusNxdomainValues: [],
            IgnoreAddressValues: [],
            AliasValues: [],
            FilterRrValues: [],
            CacheRrValues: [],
            AuthServerValues: [],
            NoDhcpInterfaceValues: [],
            NoDhcpv4InterfaceValues: [],
            NoDhcpv6InterfaceValues: [],
            DomainValues: [],
            CnameValues: [],
            MxHostValues: [],
            SrvValues: [],
            PtrRecordValues: [],
            TxtRecordValues: [],
            NaptrRecordValues: [],
            HostRecordValues: [],
            DynamicHostValues: [],
            InterfaceNameValues: [],
            DhcpOptionForceLines: [],
            IpsetValues: [],
            NftsetValues: [],
            DhcpMacValues: [],
            DhcpNameMatchValues: [],
            DhcpIgnoreNamesValues: [],
            DhcpHostsfilePaths: [],
            DhcpOptsfilePaths: [],
            DhcpHostsdirPaths: [],
            DhcpOptsdirPaths: [],
            ConnmarkAllowlistValues: [],
            CaaRecordValues: [],
            DnsRrValues: [],
            SynthDomainValues: [],
            AuthZoneValues: [],
            AuthSoaValues: [],
            AuthSecServersValues: [],
            AuthPeerValues: [],
            DhcpRelayValues: [],
            DhcpCircuitidValues: [],
            DhcpRemoteidValues: [],
            DhcpSubscridValues: [],
            DhcpProxyValues: [],
            TagIfValues: [],
            BridgeInterfaceValues: [],
            SharedNetworkValues: [],
            DhcpOptionPxeValues: [],
            ExpandHosts: null,
            BogusPriv: null,
            StrictOrder: null,
            AllServers: null,
            NoResolv: null,
            DomainNeeded: null,
            NoPoll: null,
            BindInterfaces: null,
            BindDynamic: null,
            NoNegcache: null,
            DnsLoopDetect: null,
            StopDnsRebind: null,
            RebindLocalhostOk: null,
            ClearOnReload: null,
            Filterwin2k: null,
            FilterA: null,
            FilterAaaa: null,
            LocaliseQueries: null,
            LogDebug: null,
            DhcpAuthoritative: null,
            LeasefileRo: null,
            EnableTftp: null,
            TftpSecure: null,
            TftpNoFail: null,
            TftpNoBlocksize: null,
            Dnssec: null,
            DnssecCheckUnsigned: null,
            ReadEthers: null,
            DhcpRapidCommit: null,
            Localmx: null,
            Selfmx: null,
            EnableRa: null,
            LogDhcp: null,
            KeepInForeground: null,
            NoDaemon: null,
            ProxyDnssec: null,
            ConnmarkAllowlistEnable: null,
            NoRoundRobin: null,
            DnssecNoTimecheck: null,
            DnssecDebug: null,
            LeasequeryValues: [],
            DhcpGenerateNames: null,
            DhcpBroadcast: null,
            DhcpSequentialIp: null,
            DhcpIgnoreClid: null,
            BootpDynamic: null,
            NoPing: null,
            ScriptArp: null,
            ScriptOnRenewal: null,
            DhcpNoOverride: null,
            QuietDhcp: null,
            QuietDhcp6: null,
            QuietRa: null,
            QuietTftp: null,
            DhcpLeaseFilePath: null,
            CacheSize: null,
            Port: null,
            LocalTtl: null,
            PidFilePath: null,
            User: null,
            Group: null,
            LogFacility: null,
            LogQueries: null,
            AuthTtl: null,
            EdnsPacketMax: null,
            QueryPort: null,
            PortLimit: null,
            MinPort: null,
            MaxPort: null,
            LogAsync: null,
            LocalService: null,
            DhcpLeaseMax: null,
            NegTtl: null,
            MaxTtl: null,
            MaxCacheTtl: null,
            MinCacheTtl: null,
            DhcpTtl: null,
            TftpRootPath: null,
            PxePrompt: null,
            EnableDbus: null,
            EnableUbus: null,
            FastDnsRetry: null,
            DhcpScriptPath: null,
            MxTarget: null,
            DnsForwardMax: null,
            DumpfilePath: null,
            Dumpmask: null,
            AddCpeId: null,
            DnssecTimestamp: null,
            DnssecLimits: null,
            DhcpAlternatePort: null,
            DhcpDuid: null,
            DhcpLuascriptPath: null,
            DhcpScriptuser: null,
            DhcpPxeVendor: null,
            UseStaleCache: null,
            AddMac: null,
            StripMac: null,
            AddSubnet: null,
            StripSubnet: null,
            Umbrella: null,
            Do0x20Encode: null,
            Conntrack: null);

    private static EffectiveDnsmasqConfig TestConfig(IReadOnlyList<string> addresses) =>
        EmptyConfig() with { AddressValues = addresses };

    private static EffectiveDnsmasqConfig EmptyConfig()
    {
        // Minimal non-null lists / defaults — only AddressValues overridden in tests
        return new EffectiveDnsmasqConfig(
            NoHosts: false,
            AddnHostsPaths: [],
            HostsdirPath: null,
            ServerValues: [],
            LocalValues: [],
            RevServerValues: [],
            AddressValues: [],
            Interfaces: [],
            ListenAddresses: [],
            ExceptInterfaces: [],
            DhcpRanges: [],
            DhcpHostLines: [],
            DhcpOptionLines: [],
            DhcpMatchValues: [],
            DhcpBootValues: [],
            DhcpIgnoreValues: [],
            DhcpVendorclassValues: [],
            DhcpUserclassValues: [],
            RaParamValues: [],
            SlaacValues: [],
            PxeServiceValues: [],
            TrustAnchorValues: [],
            ResolvFiles: [],
            RebindDomainOkValues: [],
            BogusNxdomainValues: [],
            IgnoreAddressValues: [],
            AliasValues: [],
            FilterRrValues: [],
            CacheRrValues: [],
            AuthServerValues: [],
            NoDhcpInterfaceValues: [],
            NoDhcpv4InterfaceValues: [],
            NoDhcpv6InterfaceValues: [],
            DomainValues: [],
            CnameValues: [],
            MxHostValues: [],
            SrvValues: [],
            PtrRecordValues: [],
            TxtRecordValues: [],
            NaptrRecordValues: [],
            HostRecordValues: [],
            DynamicHostValues: [],
            InterfaceNameValues: [],
            DhcpOptionForceLines: [],
            IpsetValues: [],
            NftsetValues: [],
            DhcpMacValues: [],
            DhcpNameMatchValues: [],
            DhcpIgnoreNamesValues: [],
            DhcpHostsfilePaths: [],
            DhcpOptsfilePaths: [],
            DhcpHostsdirPaths: [],
            DhcpOptsdirPaths: [],
            ConnmarkAllowlistValues: [],
            CaaRecordValues: [],
            DnsRrValues: [],
            SynthDomainValues: [],
            AuthZoneValues: [],
            AuthSoaValues: [],
            AuthSecServersValues: [],
            AuthPeerValues: [],
            DhcpRelayValues: [],
            DhcpCircuitidValues: [],
            DhcpRemoteidValues: [],
            DhcpSubscridValues: [],
            DhcpProxyValues: [],
            TagIfValues: [],
            BridgeInterfaceValues: [],
            SharedNetworkValues: [],
            DhcpOptionPxeValues: [],
            ExpandHosts: false,
            BogusPriv: false,
            StrictOrder: false,
            AllServers: false,
            NoResolv: false,
            DomainNeeded: false,
            NoPoll: false,
            BindInterfaces: false,
            BindDynamic: false,
            NoNegcache: false,
            DnsLoopDetect: false,
            StopDnsRebind: false,
            RebindLocalhostOk: false,
            ClearOnReload: false,
            Filterwin2k: false,
            FilterA: false,
            FilterAaaa: false,
            LocaliseQueries: false,
            LogDebug: false,
            DhcpAuthoritative: false,
            LeasefileRo: false,
            EnableTftp: false,
            TftpSecure: false,
            TftpNoFail: false,
            TftpNoBlocksize: false,
            Dnssec: false,
            DnssecCheckUnsigned: null,
            ReadEthers: false,
            DhcpRapidCommit: false,
            Localmx: false,
            Selfmx: false,
            EnableRa: false,
            LogDhcp: false,
            KeepInForeground: false,
            NoDaemon: false,
            ProxyDnssec: false,
            ConnmarkAllowlistEnable: null,
            NoRoundRobin: false,
            DnssecNoTimecheck: false,
            DnssecDebug: false,
            LeasequeryValues: [],
            DhcpGenerateNames: null,
            DhcpBroadcast: null,
            DhcpSequentialIp: false,
            DhcpIgnoreClid: false,
            BootpDynamic: null,
            NoPing: false,
            ScriptArp: false,
            ScriptOnRenewal: false,
            DhcpNoOverride: false,
            QuietDhcp: false,
            QuietDhcp6: false,
            QuietRa: false,
            QuietTftp: false,
            DhcpLeaseFilePath: null,
            CacheSize: null,
            Port: null,
            LocalTtl: null,
            PidFilePath: null,
            User: null,
            Group: null,
            LogFacility: null,
            LogQueries: null,
            AuthTtl: null,
            EdnsPacketMax: null,
            QueryPort: null,
            PortLimit: null,
            MinPort: null,
            MaxPort: null,
            LogAsync: null,
            LocalService: null,
            DhcpLeaseMax: null,
            NegTtl: null,
            MaxTtl: null,
            MaxCacheTtl: null,
            MinCacheTtl: null,
            DhcpTtl: null,
            TftpRootPath: null,
            PxePrompt: null,
            EnableDbus: null,
            EnableUbus: null,
            FastDnsRetry: null,
            DhcpScriptPath: null,
            MxTarget: null,
            DnsForwardMax: null,
            DumpfilePath: null,
            Dumpmask: null,
            AddCpeId: null,
            DnssecTimestamp: null,
            DnssecLimits: null,
            DhcpAlternatePort: null,
            DhcpDuid: null,
            DhcpLuascriptPath: null,
            DhcpScriptuser: null,
            DhcpPxeVendor: null,
            UseStaleCache: null,
            AddMac: null,
            StripMac: false,
            AddSubnet: null,
            StripSubnet: false,
            Umbrella: null,
            Do0x20EncodeState: ExplicitToggleState.Default,
            Conntrack: false);
    }

    private static DnsmasqServiceStatus EmptyStatus() =>
        new(
            SystemHostsPath: null,
            SystemHostsPathExists: false,
            ManagedHostsFilePath: null,
            ManagedHostsPathExists: false,
            NoHosts: false,
            AddnHostsPaths: [],
            EffectiveConfig: null,
            EffectiveConfigSources: null,
            MainConfigPath: null,
            ManagedFilePath: "/managed.conf",
            LeasesPath: null,
            MainConfigPathExists: false,
            ManagedFilePathExists: true,
            LeasesPathConfigured: false,
            LeasesPathExists: false,
            ConfigFiles: [],
            ReloadCommandConfigured: false,
            StatusCommandConfigured: false,
            StatusShowConfigured: false,
            LogsConfigured: false,
            LogsPath: null,
            StatusShowCommand: null,
            LogsCommand: null,
            DnsmasqStatus: "active",
            StatusCommandExitCode: null,
            StatusCommandStdout: null,
            StatusCommandStderr: null,
            StatusShowOutput: null,
            LogsOutput: null,
            DhcpRangeStart: null,
            DhcpRangeEnd: null,
            DnsmasqVersion: null,
            MinimumSupportedDnsmasqVersion: "0",
            DnsmasqVersionSupported: true,
            DnsmasqVersionError: null,
            DnsmasqSupportsDhcp: false,
            DnsmasqSupportsTftp: false,
            DnsmasqSupportsDnssec: false,
            DnsmasqSupportsDbus: false);

    [Fact]
    public void BuildGroups_MarksManagedAddressEditable()
    {
        var managed = new ConfigValueSource("/managed.conf", "managed.conf", IsManaged: true, 10);
        var status = MinimalStatus(
            ["/ads.example/#"],
            [new ValueWithSource("/ads.example/#", managed)]);

        var svc = new FiltersPageProjectionService(new FilterPolicySummaryFormatter());
        var groups = svc.BuildGroups(status, new FilterPolicyQueryState("", null, null, null, null));
        var blocking = groups.First(g => g.Category == FilterPolicyCategory.Blocking);
        var row = Assert.Single(blocking.Rows);
        Assert.True(row.IsEditable);
        Assert.Equal(FilterPolicyKind.Address, row.Kind);
    }

    [Fact]
    public void BuildGroups_ReadOnlyWhenSourceNotManaged()
    {
        var ro = new ConfigValueSource("/etc/dnsmasq.d/z.conf", "z.conf", IsManaged: false, 2);
        var status = MinimalStatus(
            ["/ads.example/#"],
            [new ValueWithSource("/ads.example/#", ro)]);

        var svc = new FiltersPageProjectionService(new FilterPolicySummaryFormatter());
        var groups = svc.BuildGroups(status, new FilterPolicyQueryState("", null, null, null, null));
        var row = Assert.Single(groups.First(g => g.Category == FilterPolicyCategory.Blocking).Rows);
        Assert.False(row.IsEditable);
    }
}
