namespace DnsmasqWebUI.Models.Dnsmasq.EffectiveConfig;

/// <summary>
/// Source file for each field in <see cref="EffectiveDnsmasqConfig"/>.
/// Same property names as config: use <c>sources.Port</c> for <c>config.Port</c>, <c>sources.AddnHostsPaths[i].Source</c> for <c>config.AddnHostsPaths[i]</c>, etc.
/// Enables the UI to show exactly where each value came from and whether it is readonly.
/// </summary>
/// <remarks>
/// <para><b>Single-value and flags:</b> Property is <see cref="ConfigValueSource"/>?. Readonly = <c>source?.IsReadOnly == true</c>. Tooltip = <see cref="ConfigValueSource.GetReadOnlyTooltip"/>.</para>
/// <para><b>Multi-value:</b> Property is <c>IReadOnlyList&lt;ValueWithSource&gt;</c> or <c>PathWithSource</c> for addn-hosts. Use <c>sources.AddnHostsPaths[i].Source</c>. Same readonly/tooltip from that Source.</para>
/// </remarks>
public record EffectiveConfigSources(
    // --- Hosts ---
    ConfigValueSource? NoHosts,
    IReadOnlyList<PathWithSource> AddnHostsPaths,
    ConfigValueSource? HostsdirPath,

    // --- Multi-value (ARG_DUP): source per value ---
    IReadOnlyList<ValueWithSource> ServerLocalValues,
    IReadOnlyList<ValueWithSource> RevServerValues,
    IReadOnlyList<ValueWithSource> AddressValues,
    IReadOnlyList<ValueWithSource> Interfaces,
    IReadOnlyList<ValueWithSource> ListenAddresses,
    IReadOnlyList<ValueWithSource> ExceptInterfaces,
    IReadOnlyList<ValueWithSource> DhcpRanges,
    IReadOnlyList<ValueWithSource> DhcpHostLines,
    IReadOnlyList<ValueWithSource> DhcpOptionLines,
    IReadOnlyList<ValueWithSource> DhcpMatchValues,
    IReadOnlyList<ValueWithSource> DhcpBootValues,
    IReadOnlyList<ValueWithSource> DhcpIgnoreValues,
    IReadOnlyList<ValueWithSource> DhcpVendorclassValues,
    IReadOnlyList<ValueWithSource> DhcpUserclassValues,
    IReadOnlyList<ValueWithSource> RaParamValues,
    IReadOnlyList<ValueWithSource> SlaacValues,
    IReadOnlyList<ValueWithSource> PxeServiceValues,
    IReadOnlyList<ValueWithSource> TrustAnchorValues,
    IReadOnlyList<ValueWithSource> ResolvFiles,
    IReadOnlyList<ValueWithSource> RebindDomainOkValues,
    IReadOnlyList<ValueWithSource> BogusNxdomainValues,
    IReadOnlyList<ValueWithSource> IgnoreAddressValues,
    IReadOnlyList<ValueWithSource> AliasValues,
    IReadOnlyList<ValueWithSource> FilterRrValues,
    IReadOnlyList<ValueWithSource> CacheRrValues,
    IReadOnlyList<ValueWithSource> AuthServerValues,
    IReadOnlyList<ValueWithSource> NoDhcpInterfaceValues,
    IReadOnlyList<ValueWithSource> NoDhcpv4InterfaceValues,
    IReadOnlyList<ValueWithSource> NoDhcpv6InterfaceValues,
    IReadOnlyList<ValueWithSource> DomainValues,
    IReadOnlyList<ValueWithSource> CnameValues,
    IReadOnlyList<ValueWithSource> MxHostValues,
    IReadOnlyList<ValueWithSource> SrvValues,
    IReadOnlyList<ValueWithSource> PtrRecordValues,
    IReadOnlyList<ValueWithSource> TxtRecordValues,
    IReadOnlyList<ValueWithSource> NaptrRecordValues,
    IReadOnlyList<ValueWithSource> HostRecordValues,
    IReadOnlyList<ValueWithSource> DynamicHostValues,
    IReadOnlyList<ValueWithSource> InterfaceNameValues,

    // --- Flags (set if any occurrence; source = first file that set it, so we know if readonly) ---
    ConfigValueSource? ExpandHosts,
    ConfigValueSource? BogusPriv,
    ConfigValueSource? StrictOrder,
    ConfigValueSource? AllServers,
    ConfigValueSource? NoResolv,
    ConfigValueSource? DomainNeeded,
    ConfigValueSource? NoPoll,
    ConfigValueSource? BindInterfaces,
    ConfigValueSource? BindDynamic,
    ConfigValueSource? NoNegcache,
    ConfigValueSource? DnsLoopDetect,
    ConfigValueSource? StopDnsRebind,
    ConfigValueSource? RebindLocalhostOk,
    ConfigValueSource? ClearOnReload,
    ConfigValueSource? Filterwin2k,
    ConfigValueSource? FilterA,
    ConfigValueSource? FilterAaaa,
    ConfigValueSource? LocaliseQueries,
    ConfigValueSource? LogDebug,
    ConfigValueSource? DhcpAuthoritative,
    ConfigValueSource? LeasefileRo,
    ConfigValueSource? EnableTftp,
    ConfigValueSource? TftpSecure,
    ConfigValueSource? Dnssec,
    ConfigValueSource? DnssecCheckUnsigned,

    // --- Single-value (last occurrence wins; source = file that set the last value) ---
    ConfigValueSource? DhcpLeaseFilePath,
    ConfigValueSource? CacheSize,
    ConfigValueSource? Port,
    ConfigValueSource? LocalTtl,
    ConfigValueSource? PidFilePath,
    ConfigValueSource? User,
    ConfigValueSource? Group,
    ConfigValueSource? LogFacility,
    ConfigValueSource? LogQueries,
    ConfigValueSource? AuthTtl,
    ConfigValueSource? EdnsPacketMax,
    ConfigValueSource? QueryPort,
    ConfigValueSource? PortLimit,
    ConfigValueSource? MinPort,
    ConfigValueSource? MaxPort,
    ConfigValueSource? LogAsync,
    ConfigValueSource? LocalService,
    ConfigValueSource? DhcpLeaseMax,
    ConfigValueSource? NegTtl,
    ConfigValueSource? MaxTtl,
    ConfigValueSource? MaxCacheTtl,
    ConfigValueSource? MinCacheTtl,
    ConfigValueSource? DhcpTtl,
    ConfigValueSource? TftpRootPath,
    ConfigValueSource? PxePrompt,
    ConfigValueSource? EnableDbus,
    ConfigValueSource? EnableUbus,
    ConfigValueSource? FastDnsRetry
);
